### ISSUE TITLE
Sync library.properties version

### ISSUE THREAD

**Issue by maxgerhardt** [jaumemirallesisern/CircusESP32Lib#4]
https://github.com/jaumemirallesisern/CircusESP32Lib/releases/tag/v1.0.2 created a new release, but 

https://github.com/jaumemirallesisern/CircusESP32Lib/blob/44affc8ac261ad50a99a0c77cfc08be062ed0cba/library.properties#L2

stayed the same.

**Comment by jaumemirallesisern** [comment]
The release is updated now. Thanks.

**Comment by maxgerhardt** [comment]
But that doesn't retroactively change the 1.0.2 tag, I think that one has to be recreated:

https://github.com/jaumemirallesisern/CircusESP32Lib/blob/v1.0.2/library.properties

**Comment by jaumemirallesisern** [comment]
Now seems to be ready.
